'use strict';
const INITIATE_CONNECTIONS = 'INITIATE_CONNECTIONS';
const START_ROUND = 'START_ROUND';
const EXIT = 'EXIT';
const PID = 'PID';
const CONNECTIONS_ESTABLISHED = 'CONNECTIONS_ESTABLISHED';
const END_ROUND = 'END_ROUND';
const TERMINATED = 'TERMINATED';

module.exports = {
  INITIATE_CONNECTIONS,
  START_ROUND,
  EXIT,
  PID,
  CONNECTIONS_ESTABLISHED,
  END_ROUND,
  TERMINATED
};
